In [120]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px

In [121]:
!pip install jovian

Collecting jovian
  Downloading jovian-0.2.47-py2.py3-none-any.whl.metadata (4.1 kB)
Requirement already satisfied: requests in /usr/lib/python3/dist-packages (from jovian) (2.31.0)
Collecting uuid (from jovian)
  Downloading uuid-1.30.tar.gz (5.8 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: pyyaml in /usr/lib/python3/dist-packages (from jovian) (6.0.1)
Requirement already satisfied: click in /usr/lib/python3/dist-packages (from jovian) (8.1.6)
Downloading jovian-0.2.47-py2.py3-none-any.whl (68 kB)
Building wheels for collected packages: uuid
  Building wheel for uuid (pyproject.toml) ... done
  Created wheel for uuid: filename=uuid-1.30-py3-none-any.whl size=6502 sha256=8d9048f746f78d65c47cad6843279a941cbdfcb924699d691945658aff2f1451
  Stored in directory: /home/selowa-mphadi/.cache/pip/wheels/35/34/36/b9f3546da107cf37bab75cdb3ce1ebd8d744648985d0111ca1
Successfully built uuid
Installing collected packages: uuid, jovian
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2/2 [jovian]
Successfully installed jovian-0.2.47 uuid-1.30

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: pip install --upgrade pip

In [125]:
df = pd.read_csv('/home/selowa-mphadi/PycharmProjects/pythonProject/optimized/data/raw data/Housing.csv')
df.head()

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,13300000,7420,4,2,3,yes,no,no,no,yes,2,yes,furnished
1,12250000,8960,4,4,4,yes,no,no,no,yes,3,no,furnished
2,12250000,9960,3,2,2,yes,no,yes,no,no,2,yes,semi-furnished
3,12215000,7500,4,2,2,yes,no,yes,no,yes,3,yes,furnished
4,11410000,7420,4,1,2,yes,yes,yes,no,yes,2,no,furnished

In [126]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 545 entries, 0 to 544
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   price             545 non-null    int64
 1   area              545 non-null    int64
 2   bedrooms          545 non-null    int64
 3   bathrooms         545 non-null    int64
 4   stories           545 non-null    int64
 5   mainroad          545 non-null    object
 6   guestroom         545 non-null    object
 7   basement          545 non-null    object
 8   hotwaterheating   545 non-null    object
 9   airconditioning   545 non-null    object
 10  parking           545 non-null    int64
 11  prefarea          545 non-null    object
 12  furnishingstatus  545 non-null    object
dtypes: int64(6), object(7)
memory usage: 55.5+ KB

In [127]:
df.describe()

,price,area,bedrooms,bathrooms,stories,parking
count,5.450000e+02,545.000000,545.000000,545.000000,545.000000,545.000000
mean,4.766729e+06,5150.541284,2.965138,1.286239,1.805505,0.693578
std,1.870440e+06,2170.141023,0.738064,0.502470,0.867492,0.861586
min,1.750000e+06,1650.000000,1.000000,1.000000,1.000000,0.000000
25%,3.430000e+06,3600.000000,2.000000,1.000000,1.000000,0.000000
50%,4.340000e+06,4600.000000,3.000000,1.000000,2.000000,0.000000
75%,5.740000e+06,6360.000000,3.000000,2.000000,2.000000,1.000000
max,1.330000e+07,16200.000000,6.000000,4.000000,4.000000,3.000000

In [128]:
#univariate analysis
numerical_cols = [
    "price", "area", "bedrooms",
    "bathrooms", "stories", "parking"
]

for col in numerical_cols:
    fig = px.histogram(
        df,
        x=col,
        nbins=30,
        title=f"Distribution of {col}",
        marginal="box"   # adds boxplot for outliers
    )
    fig.show()

In [129]:
categorical_cols = [
    "mainroad", "guestroom", "basement",
    "hotwaterheating", "airconditioning",
    "prefarea", "furnishingstatus"
]

In [130]:
#univariate analysis of categorical columns
for col in categorical_cols:
    fig = px.bar(
        df[col].value_counts().reset_index(),
        x="count",
        y=col,
        labels={"index": col, col: "category"},
        title=f"Distribution of {col}"
    )
    fig.show()

In [131]:
# Make a new column for log-transformed price
df["price_log"] = np.log(df["price"])

# If your data might have zeros or negative values, use log1p
# df["price_log"] = np.log1p(df["price"])

In [132]:
df.drop(columns='price', inplace=True)

In [133]:
df

,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus,price_log
0,7420,4,2,3,yes,no,no,no,yes,2,yes,furnished,16.403275
1,8960,4,4,4,yes,no,no,no,yes,3,no,furnished,16.321036
2,9960,3,2,2,yes,no,yes,no,no,2,yes,semi-furnished,16.321036
3,7500,4,2,2,yes,no,yes,no,yes,3,yes,furnished,16.318175
4,7420,4,1,2,yes,yes,yes,no,yes,2,no,furnished,16.250001
...,...,...,...,...,...,...,...,...,...,...,...,...,...
540,3000,2,1,1,yes,no,yes,no,no,2,no,unfurnished,14.414347
541,2400,3,1,1,no,no,no,no,no,0,no,semi-furnished,14.384879
542,3620,2,1,1,yes,no,no,no,no,0,no,unfurnished,14.375126
543,2910,3,1,1,no,no,no,no,no,0,no,furnished,14.375126
544,3850,3,1,2,yes,no,no,no,no,0,no,unfurnished,14.375126

In [134]:
#defined my input and target columns
X = df.drop("price_log", axis=1)
y = df["price_log"]

In [135]:
#split the data into training sets and validation sets
from sklearn.model_selection import train_test_split

X_train, X_val, y_train, y_val = train_test_split(
    X,
    y,
    test_size=0.30,
    random_state=42
)

In [136]:
#validate the split
print("Training set size:", X_train.shape)
print("Validation set size:", X_val.shape)

Training set size: (381, 12)
Validation set size: (164, 12)

In [137]:
#combine and save to parquet
train_df = X_train.copy()
train_df["price"] = y_train.values

val_df = X_val.copy()
val_df["price"] = y_val.values

train_df.to_parquet("training_data.parquet", index=False)
val_df.to_parquet("val_data.parquet", index=False)

In [138]:
train_df

,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus,price
126,7160,3,1,1,yes,no,yes,no,no,2,yes,unfurnished,15.587067
363,3584,2,1,1,yes,no,no,yes,no,0,no,semi-furnished,15.126542
370,4280,2,1,1,yes,no,no,no,yes,2,no,semi-furnished,15.107494
31,7000,3,1,4,yes,no,no,no,yes,2,no,semi-furnished,15.943742
113,9620,3,1,1,yes,no,yes,no,no,2,yes,furnished,15.621009
...,...,...,...,...,...,...,...,...,...,...,...,...,...
71,6000,4,2,4,yes,no,no,no,yes,0,no,unfurnished,15.725794
106,5450,4,2,1,yes,no,yes,no,yes,0,yes,semi-furnished,15.633587
270,4500,3,2,3,yes,no,no,yes,no,1,no,furnished,15.283385
435,4040,2,1,1,yes,no,no,no,no,0,no,unfurnished,15.006398
102,5500,3,2,4,yes,yes,no,no,yes,1,no,semi-furnished,15.639253

In [139]:
#bivariate analysis for numerical cols

numerical_cols = ["area", "bedrooms", "bathrooms", "stories", "parking"]

for col in numerical_cols:
    fig = px.scatter(
        df,
        x=col,
        y="price_log",
        #trendline="ols",
        title=f"Price vs {col}",
        labels={col: col.capitalize(), "price": "House Price"}
    )
    fig.show()

In [140]:
#bivariate analysis forf categorical columns
binary_cols = [
    "mainroad", "guestroom", "basement",
    "hotwaterheating", "airconditioning", "prefarea"
]

for col in binary_cols:
    fig = px.box(
        df,
        x=col,
        y="price_log",
        title=f"Price Distribution by {col}",
        labels={col: col.capitalize(), "price": "House Price"}
    )
    fig.show()

In [141]:
fig = px.violin(
    df,
    x="furnishingstatus",
    y="price_log",
    box=True,
    points="all",
    title="Price Distribution by Furnishing Status"
)
fig.show()

In [142]:
#outlier detection on prices
Q1 = df["price_log"].quantile(0.25)
Q3 = df["price_log"].quantile(0.75)
IQR = Q3 - Q1

outliers = df[
    (df["price_log"] < Q1 - 1.5 * IQR) |
    (df["price_log"] > Q3 + 1.5 * IQR)
]

len(outliers)

1

In [143]:
#outlier detection for area column
Q1 = df["area"].quantile(0.25)
Q3 = df["area"].quantile(0.75)
IQR = Q3 - Q1

outliers = df[
    (df["area"] < Q1 - 1.5 * IQR) |
    (df["area"] > Q3 + 1.5 * IQR)
]

len(outliers)

12

In [144]:
train_df

,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus,price
126,7160,3,1,1,yes,no,yes,no,no,2,yes,unfurnished,15.587067
363,3584,2,1,1,yes,no,no,yes,no,0,no,semi-furnished,15.126542
370,4280,2,1,1,yes,no,no,no,yes,2,no,semi-furnished,15.107494
31,7000,3,1,4,yes,no,no,no,yes,2,no,semi-furnished,15.943742
113,9620,3,1,1,yes,no,yes,no,no,2,yes,furnished,15.621009
...,...,...,...,...,...,...,...,...,...,...,...,...,...
71,6000,4,2,4,yes,no,no,no,yes,0,no,unfurnished,15.725794
106,5450,4,2,1,yes,no,yes,no,yes,0,yes,semi-furnished,15.633587
270,4500,3,2,3,yes,no,no,yes,no,1,no,furnished,15.283385
435,4040,2,1,1,yes,no,no,no,no,0,no,unfurnished,15.006398
102,5500,3,2,4,yes,yes,no,no,yes,1,no,semi-furnished,15.639253

In [145]:
#binary encoding
binary_cols = [
    "mainroad",
    "guestroom",
    "basement",
    "hotwaterheating",
    "airconditioning",
    "prefarea"
]

binary_map = {"no": 0, "yes": 1}
# Training set
for col in binary_cols:
    train_df[col] = train_df[col].map(binary_map)

# Validation set
for col in binary_cols:
    val_df[col] = val_df[col].map(binary_map)

In [146]:
train_encoded = pd.get_dummies(train_df, columns=['furnishingstatus'], dtype=int)
train_encoded

,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,price,furnishingstatus_furnished,furnishingstatus_semi-furnished,furnishingstatus_unfurnished
126,7160,3,1,1,1,0,1,0,0,2,1,15.587067,0,0,1
363,3584,2,1,1,1,0,0,1,0,0,0,15.126542,0,1,0
370,4280,2,1,1,1,0,0,0,1,2,0,15.107494,0,1,0
31,7000,3,1,4,1,0,0,0,1,2,0,15.943742,0,1,0
113,9620,3,1,1,1,0,1,0,0,2,1,15.621009,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
71,6000,4,2,4,1,0,0,0,1,0,0,15.725794,0,0,1
106,5450,4,2,1,1,0,1,0,1,0,1,15.633587,0,1,0
270,4500,3,2,3,1,0,0,1,0,1,0,15.283385,1,0,0
435,4040,2,1,1,1,0,0,0,0,0,0,15.006398,0,0,1
102,5500,3,2,4,1,1,0,0,1,1,0,15.639253,0,1,0

In [147]:
val_encoded = pd.get_dummies(val_df, columns=['furnishingstatus'], dtype=int)
val_encoded

,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,price,furnishingstatus_furnished,furnishingstatus_semi-furnished,furnishingstatus_unfurnished
316,5900,4,2,2,0,0,1,0,0,1,0,15.216694,0,0,1
77,6500,3,2,3,1,0,0,0,1,0,1,15.710127,1,0,0
360,4040,2,1,1,1,0,0,0,0,0,0,15.126542,0,1,0
90,5000,3,1,2,1,0,0,0,1,0,0,15.678039,0,1,0
493,3960,3,1,1,1,0,0,0,0,0,0,14.845130,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
395,3600,6,1,2,1,0,0,0,0,1,0,15.068274,0,0,1
425,3185,2,1,1,1,0,1,0,0,2,0,15.027452,1,0,0
195,4410,4,3,2,1,0,1,0,0,2,0,15.418930,0,1,0
452,9000,3,1,2,1,0,0,0,0,2,0,14.962913,0,1,0
154,3650,3,2,2,1,0,0,0,0,2,0,15.525698,0,1,0

In [148]:
from sklearn.model_selection import train_test_split

# Features (drop original price columns if using log-transformed target)
X = df.drop(["price_log"], axis=1)
y = df["price_log"]

In [149]:
train_encoded

,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,price,furnishingstatus_furnished,furnishingstatus_semi-furnished,furnishingstatus_unfurnished
126,7160,3,1,1,1,0,1,0,0,2,1,15.587067,0,0,1
363,3584,2,1,1,1,0,0,1,0,0,0,15.126542,0,1,0
370,4280,2,1,1,1,0,0,0,1,2,0,15.107494,0,1,0
31,7000,3,1,4,1,0,0,0,1,2,0,15.943742,0,1,0
113,9620,3,1,1,1,0,1,0,0,2,1,15.621009,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
71,6000,4,2,4,1,0,0,0,1,0,0,15.725794,0,0,1
106,5450,4,2,1,1,0,1,0,1,0,1,15.633587,0,1,0
270,4500,3,2,3,1,0,0,1,0,1,0,15.283385,1,0,0
435,4040,2,1,1,1,0,0,0,0,0,0,15.006398,0,0,1
102,5500,3,2,4,1,1,0,0,1,1,0,15.639253,0,1,0

In [150]:
train_encoded.describe()

,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,price,furnishingstatus_furnished,furnishingstatus_semi-furnished,furnishingstatus_unfurnished
count,381.000000,381.000000,381.000000,381.000000,381.000000,381.000000,381.000000,381.000000,381.000000,381.000000,381.000000,381.000000,381.000000,381.000000,381.000000
mean,5128.401575,2.958005,1.262467,1.782152,0.863517,0.186352,0.359580,0.052493,0.317585,0.669291,0.236220,15.313419,0.262467,0.427822,0.309711
std,2177.317846,0.752763,0.475044,0.862857,0.343752,0.389902,0.480508,0.223313,0.466149,0.837180,0.425318,0.351112,0.440554,0.495413,0.462983
min,1650.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,14.375126,0.000000,0.000000,0.000000
25%,3600.000000,2.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,15.068274,0.000000,0.000000,0.000000
50%,4500.000000,3.000000,1.000000,2.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,15.293016,0.000000,0.000000,0.000000
75%,6325.000000,3.000000,1.000000,2.000000,1.000000,0.000000,1.000000,0.000000,1.000000,1.000000,0.000000,15.562970,1.000000,1.000000,1.000000
max,16200.000000,6.000000,4.000000,4.000000,1.000000,1.000000,1.000000,1.000000,1.000000,3.000000,1.000000,16.321036,1.000000,1.000000,1.000000

In [151]:
val_encoded

,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,price,furnishingstatus_furnished,furnishingstatus_semi-furnished,furnishingstatus_unfurnished
316,5900,4,2,2,0,0,1,0,0,1,0,15.216694,0,0,1
77,6500,3,2,3,1,0,0,0,1,0,1,15.710127,1,0,0
360,4040,2,1,1,1,0,0,0,0,0,0,15.126542,0,1,0
90,5000,3,1,2,1,0,0,0,1,0,0,15.678039,0,1,0
493,3960,3,1,1,1,0,0,0,0,0,0,14.845130,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
395,3600,6,1,2,1,0,0,0,0,1,0,15.068274,0,0,1
425,3185,2,1,1,1,0,1,0,0,2,0,15.027452,1,0,0
195,4410,4,3,2,1,0,1,0,0,2,0,15.418930,0,1,0
452,9000,3,1,2,1,0,0,0,0,2,0,14.962913,0,1,0
154,3650,3,2,2,1,0,0,0,0,2,0,15.525698,0,1,0

In [152]:
numerical_cols = ["area", "bedrooms", "bathrooms", "stories", "parking"]
X_train = train_encoded.drop(["price"], axis=1)
y_train = train_encoded['price']


X_val = val_encoded.drop(["price"], axis=1)
y_val = val_encoded['price']

In [153]:
from sklearn.preprocessing import StandardScaler

# Initialize scaler
scaler = StandardScaler()

# Fit scaler on training set and transform training set
X_train_scaled = X_train.copy()  # keep original intact
X_train_scaled[numerical_cols] = scaler.fit_transform(X_train[numerical_cols])

# Transform validation set using the same scaler
X_val_scaled = X_val.copy()
X_val_scaled[numerical_cols] = scaler.transform(X_val[numerical_cols])

In [156]:
#done building the prepocessing now i can build an actual model and test after optimize the model
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score

# Initialize model
lr_model = LinearRegression()

# Train model
lr_model.fit(X_train_scaled, y_train)

LinearRegression()

In [169]:
#make a predicction on train set
y_train_pred = lr_model.predict(X_train_scaled)
#y_train_pred_price = np.exp(y_train_pred)
y_train_pred

array([15.40156425, 15.10143104, 15.26075647, 15.67559588, 15.6355436 ,
       15.62955731, 15.02977125, 15.3588306 , 16.09255452, 15.46503199,
       15.77880295, 15.9314707 , 14.99630194, 15.75780669, 15.46762249,
       15.31260386, 15.09297818, 15.24019196, 15.64457395, 15.50707428,
       15.4417564 , 15.17704456, 15.68798811, 15.0338775 , 15.05364255,
       14.93337932, 16.03563938, 15.53379825, 15.62584989, 15.28380387,
       15.36404227, 15.81046259, 15.37094972, 15.25055862, 14.9014498 ,
       16.0021298 , 15.32633698, 15.41384392, 15.51378368, 15.51200723,
       14.86144695, 15.54482223, 15.00913148, 15.2879904 , 15.80635041,
       15.51059442, 15.58564622, 15.98866445, 16.04712325, 15.6056891 ,
       15.68607697, 15.23448637, 15.97966979, 15.37331624, 15.02675624,
       15.50941347, 15.20353985, 15.42546046, 15.08208087, 15.21283187,
       15.78103429, 15.0375223 , 15.15272179, 15.53388618, 15.60854087,
       14.98964019, 15.05225049, 15.37733901, 15.38168118, 15.51584388,
       15.14258089, 15.78921241, 15.10825904, 15.39416267, 15.26690419,
       15.41222021, 15.40250132, 15.31087739, 15.11098241, 14.95038607,
       14.8993878 , 15.22968107, 15.60454681, 15.67903964, 15.219906  ,
       15.33272726, 15.70262945, 15.64551346, 15.28165356, 14.9923579 ,
       15.24806584, 15.40416183, 14.87335479, 15.12513076, 15.69846568,
       15.48745009, 15.39209847, 15.16050877, 15.03443056, 15.64340935,
       15.05169835, 15.26116638, 15.38287571, 15.17422877, 15.32595165,
       14.92365297, 15.13001829, 15.23640065, 15.2534254 , 15.82247046,
       15.66395957, 15.16793076, 15.49190832, 15.8134258 , 15.54989673,
       15.3359626 , 15.20553514, 15.17555349, 14.91407935, 15.47988995,
       15.1671029 , 15.12993936, 15.5714529 , 15.37329963, 15.3553599 ,
       15.20353985, 15.39575901, 15.1974976 , 15.42824209, 15.34593838,
       15.25315024, 15.49035772, 14.82899737, 15.55464628, 15.47729007,
       15.16198069, 15.26839705, 15.6222786 , 14.89112124, 14.85891809,
       15.23337628, 15.62445014, 15.39033132, 15.18379673, 15.11148173,
       15.16360732, 15.47907081, 15.02522207, 14.8993878 , 15.20681235,
       15.32946742, 15.86672735, 15.41223289, 15.53525823, 14.95614613,
       15.27745564, 15.78679462, 14.94887587, 15.24952738, 14.73729621,
       14.88031427, 15.1004724 , 14.9417318 , 15.39468062, 15.21386326,
       14.98799595, 14.9217875 , 14.92698079, 15.37952462, 15.35758219,
       15.15805837, 15.55978623, 15.28767341, 15.14681192, 15.49791142,
       15.11451706, 15.24345626, 14.87876777, 15.09159697, 15.76417256,
       15.33863145, 15.51879059, 15.43214521, 15.16923598, 15.21682633,
       15.75369498, 15.53653594, 15.04212551, 15.55768988, 14.89642292,
       15.11380171, 14.9723707 , 15.53926545, 14.91533202, 15.31461196,
       15.1021491 , 14.95169143, 15.43367742, 14.93805035, 14.98593394,
       15.26788733, 14.85711674, 15.7760833 , 15.48150309, 15.85091787,
       15.1540265 , 15.73664425, 15.23118904, 15.57466083, 15.06766227,
       15.48229986, 15.74355081, 15.85414559, 15.76402047, 15.41216662,
       15.70841651, 14.90033095, 15.01195189, 15.29450573, 15.62577729,
       15.47950385, 15.26098041, 14.90892434, 14.99112724, 15.31186492,
       15.56982402, 14.95713884, 15.82533544, 15.05481451, 15.02495177,
       15.41793378, 15.11772221, 15.11465423, 15.08699567, 15.15343538,
       15.40152749, 15.03748402, 15.72303865, 15.21091696, 15.41960678,
       15.59526931, 15.48338671, 14.92000783, 15.40855789, 14.90023377,
       15.50832944, 15.6464749 , 15.14927102, 15.09819264, 15.44895054,
       15.1184246 , 15.80077327, 15.65226889, 15.21460005, 15.32117929,
       15.39867358, 14.73265671, 15.3344142 , 15.02054742, 15.27003819,
       15.25548437, 15.4632659 , 15.31312015, 15.23710245, 15.73718314,
       15.18547062, 14.85151917, 15.39055681, 15.62032255, 15.5975568 ,
       15.51984138, 14.76487572, 15.86014714, 14.95577659, 15.00401476,
       15.80347034, 15.20637655, 15.59992542, 15.46241472, 15.60018137,
       15.0969948 , 15.49811074, 14.97675223, 15.33926045, 14.95524703,
       15.12821214, 15.043728  , 15.07344413, 15.25133515, 15.31631025,
       15.32031747, 15.64600809, 14.92134983, 15.02649827, 15.25574862,
       14.91028581, 15.1158064 , 14.87979877, 15.17168025, 15.22597948,
       15.00072324, 14.95577737, 15.32598984, 15.60908289, 15.69351022,
       15.59721035, 15.53826689, 15.55562392, 15.30994406, 15.43077824,
       15.33648869, 15.76397125, 15.17159181, 16.39403006, 14.73033673,
       14.9501281 , 15.8106974 , 15.16367471, 15.48345716, 15.38731168,
       15.6666274 , 14.84822382, 15.0060466 , 15.23640065, 15.16835593,
       14.87670264, 15.10440763, 15.52493739, 15.27694042, 14.88082977,
       15.83584986, 15.23489244, 15.2591359 , 15.11967185, 15.50243758,
       15.23093003, 15.61092097, 15.26731237, 15.20756598, 15.57125894,
       15.47084406, 14.78571698, 15.5056757 , 15.21047604, 14.73935822,
       14.8167213 , 14.99407714, 15.52468045, 15.15522399, 15.05418646,
       15.04426358, 14.75353426, 15.92764728, 14.98484269, 15.33625475,
       15.67946426, 15.28548469, 14.87361276, 15.61399611, 15.08130357,
       15.64031694, 14.88082977, 15.30292521, 14.87484063, 15.01587127,
       15.28647247, 15.13974566, 15.49421701, 15.08235232, 15.24690905,
       14.99814573, 15.26477987, 15.03435751, 14.96078563, 15.70024682,
       15.46066206, 15.61998086, 15.67077026, 15.56669371, 14.9014498 ,
       15.79284406])

In [165]:
y_train

126    15.587067
363    15.126542
370    15.107494
31     15.943742
113    15.621009
         ...
71     15.725794
106    15.633587
270    15.283385
435    15.006398
102    15.639253
Name: price, Length: 381, dtype: float64

In [170]:
# Predict on validation data
y_val_pred_log = lr_model.predict(X_val_scaled)
y_val_pred_price = np.exp(y_val_pred_log)
y_val_pred_log

array([15.36531238, 15.74848607, 15.01380927, 15.30649043, 15.02691603,
       15.06202806, 15.49655955, 15.64899423, 14.85837106, 14.85142142,
       16.24900949, 14.89598549, 14.91111491, 15.07822831, 15.12125892,
       15.30351576, 14.99271351, 15.2946173 , 15.26710933, 15.11484741,
       15.46534917, 15.59525111, 14.88129372, 15.32325268, 15.51699513,
       15.9260733 , 15.02917097, 15.42193108, 16.04086189, 15.03907028,
       15.65766498, 15.00945045, 15.68042315, 15.25304115, 15.06825361,
       15.51854967, 15.42610534, 15.23966107, 14.92116695, 15.25668124,
       15.33721316, 15.01701692, 15.74436206, 15.1722907 , 15.15350997,
       15.1821986 , 15.70991627, 15.22259009, 15.10816559, 15.06263745,
       15.7714657 , 14.896774  , 15.24983402, 15.28710106, 15.12667146,
       14.86224694, 15.79542655, 14.92339813, 15.26695945, 14.88907778,
       15.36801893, 14.98293884, 15.4210409 , 15.2025057 , 15.27591332,
       15.31486683, 15.79550793, 15.07125535, 15.5700642 , 15.62993652,
       15.23877877, 15.42601671, 15.28231056, 15.95241704, 15.01718682,
       15.44893639, 15.19703672, 15.29251766, 15.31771709, 15.11704252,
       15.86156565, 15.22023426, 15.66666686, 15.44656494, 14.88731308,
       15.70003239, 14.85995177, 15.13882144, 15.91620873, 15.99694279,
       15.0614741 , 15.60008848, 15.08130158, 15.1139843 , 15.85935041,
       15.31647266, 15.46279463, 15.58724679, 15.31826045, 15.59335019,
       15.1769322 , 15.6220592 , 15.14920752, 15.56656584, 15.45856164,
       15.22490495, 15.7812766 , 15.65048633, 15.63783034, 15.75365925,
       15.78331319, 15.34857113, 15.15320526, 14.99299073, 15.28723047,
       14.99814573, 14.86673822, 14.76899929, 15.13830247, 15.19038792,
       15.09012307, 15.33043706, 15.21299836, 15.17577293, 15.51967488,
       14.8411497 , 15.4337511 , 14.98777779, 15.93617854, 15.70427682,
       15.06668764, 15.40086683, 15.74602193, 15.64402039, 14.98783572,
       14.77003051, 15.03417133, 15.46099549, 14.98574787, 15.19554811,
       14.90657858, 15.18615404, 15.45024731, 15.14530995, 15.15967937,
       14.78523778, 15.71442524, 15.40655476, 15.7921122 , 15.84216904,
       15.49059644, 15.28361013, 15.16255607, 15.10511236, 15.02982643,
       15.8716522 , 15.96347202, 15.18542941, 15.72017338, 15.10146666,
       15.17934038, 15.74408302, 15.47386061, 15.38181072])

In [174]:
y_val

316    15.216694
77     15.710127
360    15.126542
90     15.678039
493    14.845130
         ...
395    15.068274
425    15.027452
195    15.418930
452    14.962913
154    15.525698
Name: price, Length: 164, dtype: float64

In [173]:
#convert back to actual prices
y_train_price = np.exp(y_train)
y_train_pred_price = np.exp(y_train_pred)
#train performance
rmse = np.sqrt(mean_squared_error(y_train_price, y_train_pred_price))
mae = mean_absolute_error(y_train_price, y_train_pred_price)
r2 = r2_score(y_train_price, y_train_pred_price)

print(f"RMSE: {rmse:.4f}")
print(f"MAE : {mae:.4f}")
print(f"R²  : {r2:.4f}\n")

#evaluate_log(y_train, y_train_pred_log, "Training Set")

RMSE: 967779.8813
MAE : 700115.0886
R²  : 0.7019

In [175]:
#vcheck model performance on validation set
#convert back to actual prices
y_val_price = np.exp(y_val)
y_val_pred_price = np.exp(y_val_pred_log)
#train performance
rmse = np.sqrt(mean_squared_error(y_val_price, y_val_pred_price))
mae = mean_absolute_error(y_val_price, y_val_pred_price)
r2 = r2_score(y_train_price, y_train_pred_price)

print(f"RMSE: {rmse:.4f}")
print(f"MAE : {mae:.4f}")
print(f"R²  : {r2:.4f}\n")

RMSE: 1218103.9719
MAE : 890026.5655
R²  : 0.7019